[project]
authors = ["johnne <john.sundh@scilifelab.se>"]
channels = ["conda-forge", "bioconda", "main"]
description = "A workflow for trimming sequencing data from amplicon sequencing"
name = "amplicon-multi-cutadapt"
platforms = ["linux-64", "osx-64"]
version = "2.0.0"

[dependencies]
python = "*"
snakemake-minimal = "8.21.0"
pandas = "*"
conda = ">=24"
snakemake-executor-plugin-slurm = "*"