# Update <your-slurm-account> and <your-slurm-partition> under default-resources
default-resources:
  slurm_account: <your-slurm-account>
  slurm_partition: <your-slurm-partition>
  cpus_per_task: 1
  runtime: 120
  mem_mb: 4000
  tasks: f"{threads}"

set-resources:
  fastqc:
    tasks: 4
  cutadapt:
    tasks: 10

# The settings below define command line flags for snakemake
keep-going: True
printshellcmds: True
rerun-triggers: mtime
rerun-incomplete: True
local-cores: 1
jobs: 100
latency-wait: 5
executor: slurm