$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  cutadapt:
    type: object
    default:
      minimum_length: 228
      expected_read_length: 251
    properties:
      minimum_length:
        type: integer
        description: "Minimum read length to keep for cutadapt"
      expected_read_length:
        type: integer
        description: "Expected read length of raw reads prior to trimming"
  primers:
    type: object
    default:
      forward:
        - "CCHGAYATRGCHTTYCCHCG"
        - "ACCHGAYATRGCHTTYCCHCG"
        - "GACCHGAYATRGCHTTYCCHCG"
        - "TGACCHGAYATRGCHTTYCCHCG"
      reverse:
        - "CDGGRTGNCCRAARAAYCA"
        - "TCDGGRTGNCCRAARAAYCA"
        - "ATCDGGRTGNCCRAARAAYCA"
        - "GATCDGGRTGNCCRAARAAYCA"
    properties:
      forward:
        type: array
        items:
          type: string
        description: "Forward primers"
      reverse:
        type: array
        items:
          type: string
        description: "Reverse primers"
  data_dir:
    type: string
    default: "data"
    description: "Top level directory for data"
  sample_list:
    type: string
    default: ""
    description: "Sample file list"
  multiqc_steps:
    type: array
    items:
      type: integer
      enum: [1,2,3,4]
    default: [4]
    description: "After which cutadapt steps do you want a multiqc report?"